config/routes.rb
Rails.application.routes.draw do
 root 'charts#index'
 devise_for :users

 resources :charts

  resources :charts do
    resources :artists
    resources :songs
  end
    
  scope 'artists/:artist_id', as: 'artist' do
    resources :songs, only: [:new, :create]
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :chart
  has_many :songs
end

app/models/chart.rb
class Chart < ApplicationRecord
  has_many :artists, dependent: :destroy
  has_many :songs, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist, optional: true
  belongs_to :chart
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  def index
    @accounts = current_user.accounts
  end

  def show
  end

  def new
    @account = Account.new
  end

  def create
    @account = current_user.accounts.new(account_params)
    if @account.save
      flash[:success] = 'Account created!'
      redirect_to accounts_path
    else
      flash[:error] = "Error: #{@account.errors.full_messages.join("/n")}"
      render :new
    end
  end

  def edit
  end

  def update
    if @account.update(account_params)
      redirect_to accounts_path
    else
      render :edit
    end
  end

  def destroy
    @account.destroy
    redirect_to accounts_path
  end

  private
    def account_params
      params.require(:account).permit(:name)
    end

    def set_account
      @account = current_user.accounts.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

protected 
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_chart
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = @chart.artists
  end

  def show
  end

  def edit
  end

  def new
    @artist = @chart.artists.new
  end

  def create
    @artist = @chart.artists.new(artist_params)
    if @artist.save
      redirect_to [@chart, @artist]
    else
      render :new
    end
  end

  def update
    if @artist.update(artist_params)
      redirect_to [@chart, @artist]
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to chart_artists_path
  end

  private

  def set_chart
      @chart = Chart.find(params[:chart_id])
    end

  def set_artist
    @artist = Artist.find(params[:id])
  end


  def artist_params
    params.require(:artist).permit(:name)
  end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  before_action :set_chart, only: [:show, :update, :edit, :destroy]

  def index
    @charts = Chart.all
  end

  def show
    @songs = @chart.songs.all
    @artists = @chart.artists.all
  end

  def new
    @chart = Chart.new
  end

  def edit
  end

  def create
    @chart = Chart.new(chart_params)

    if @chart.save
      redirect_to charts_path
    else
      render :new
    end
  end

  def update
    if @chart.update(chart_params)
    redirect_to @chart
    else
      render :edit
    end
  end

  def destroy
    @chart.destroy
    redirect_to charts_path
  end

  private

  def set_chart
    @chart = Chart.find(params[:id])
  end

  def chart_params
    params.require(:chart).permit(:name)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_chart
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  def index
    @songs = @chart.songs
  end

  def show
  end

  def edit
  end

  def new
    @song = @chart.songs.new
  end

  def create
    @song = @chart.songs.new(song_params)
    if @song.save
      redirect_to [@chart, @song]
    else
      render :new
    end
  end

  def update
    if @song.update(song_params)
      redirect_to [@chart, @song]
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to chart_songs_path
  end

  private

  def set_chart
      @chart = Chart.find(params[:chart_id])
    end

  def set_song
    @song = Song.find(params[:id])
  end


  def song_params
    params.require(:song).permit(:name)
  end
  end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/accounts/index.html.erb
<%= button_to 'Log Out', destroy_user_session_path, method: :delete %>
<h2>Welcome <%= current_user.first_name %></h2>
<hr />

app/views/artists/_form.html.erb
<%= form_for [@chart ,@artist] do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
<%= f.submit %>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit A Artist</h1>
<%= render 'form' %>

app/views/artists/index.html.erb
<h2>Browse Artists</h2>
<h3>
<ul>
  <% @artists.each do |artist| %>
    <li> <%= link_to artist.name, [artist.chart, artist] %></li>
  <% end %>
</ul></h3>
<button class="silver btn-small"><%= link_to 'Create a new Artist', new_chart_artist_path(@chart) %></button>
<button class="silver btn-small"><%= link_to 'Back', chart_path(@chart) %></button>

app/views/artists/new.html.erb
<h1>Make an Artist</h1>
<%= render 'form' %>

app/views/artists/show.html.erb
<h3><%= @artist.name %></h3>

<div class= right>
  <button class="silver btn-small"><%= link_to 'Edit', edit_chart_artist_path([@chart, @artist])%></button>
  <button class="silver btn-small"><%= link_to 'Delete', [@chart, @artist], method: :delete%></button>
  <button class="silver btn-small"><%= link_to 'Back', chart_artists_path(@chart)%></button>
</div>

app/views/charts/_form.html.erb
<%= form_for @chart do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br/>
<%= f.submit %>
<% end %>

app/views/charts/edit.html.erb
<h1>Edit A Chart</h1>
<%= render 'form' %>
<br  /> 
<button class="silver btn-small"><%= link_to 'Cancel', charts_path %></button>

app/views/charts/index.html.erb
<h4>Billboard Top Charts</h4>
<h3><ul>
  <% @charts.each do |chart| %>
    <li class="center black-text"><%= link_to "#{chart.name}", chart %></li>
		<% end %>
</ul></h3>
<button class="silver btn-small"><%= link_to 'Create a new Chart', new_chart_path %> </button>

<div class="center">
<iframe src="https://open.spotify.com/embed?uri=spotify%3Aalbum%3A2rp5riHULWgrXPsDtsp1ir" width="300" height="380" frameborder="0" allowtransparency="true"></iframe>
</div>

app/views/charts/new.html.erb
<h1>Make A New Chart</h1>
<%= render 'form' %>
<button class="silver btn-small"><%= link_to 'Cancel', charts_path %></button>

app/views/charts/show.html.erb
<h1><%= @chart.name %></h1>
<hr />

<h3>Artists:</h3>
<h5><% @artists.each_with_index do |artist, index| %>
  <span><h5> <%= index + 1%>)
  <%= artist.name %></h5></span>

  <% end %>
</h5>
<h3>Songs:</h3>
<h5><% @songs.each_with_index do |song, index| %>
  <span><h5> <%= index + 1%>)
  <%= song.name %></h5></span>
  <br  />
  <% end %>
</h5>
<button class="silver btn-small"><%= link_to 'View Songs', chart_songs_path(@chart) %></button>
<button class="silver btn-small"><%= link_to 'View Artists', chart_artists_path(@chart) %></button>
<button class="silver btn-small"><%= link_to 'Edit Chart', edit_chart_path(@chart) %> </button>
<button class="silver btn-small"><%= link_to 'Delete Chart', @chart, method: :delete %> </button>
<br  />
<br />
<button class="silver btn-small"><%= link_to 'Back', charts_path %></button>

app/views/layouts/_navbar.html.erb
<div class="nav-wrapper">
  <nav class="black accent-1">
    <a href="/" class="brand-logo">Top Charts</a>
    <a href="#" data-activates="mobile" class="button-collapse"><h1>Top Charts</h1></a>
    <p class="right ">
    <%= link_to 'Exit', destroy_user_session_path, method: :delete%>
    </p>

      <div class="center">
    <%= image_tag("Billboard-white.png", :alt => "Billboard logo") %>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billboard</title>


  <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>
  
  <body class="grey lighten-4">

      <%= render 'layouts/navbar' %>
    <%= yield %>

    </div>
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_for [@chart ,@song] do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
<%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit A Song</h1>
<%= render 'form' %>

app/views/songs/index.html.erb
<h2>Browse Songs</h2>
<h3>
<ul>
  <% @songs.each do |song| %>
    <li> <%= link_to song.name, [song.chart, song] %></li>
  <% end %>
</ul></h3>
<button class="silver btn-small"><%= link_to 'Create a new Song', new_chart_song_path(@chart) %></button>
<button class="silver btn-small"><%= link_to 'Back', chart_path(@chart) %></button>

app/views/songs/new.html.erb
<h1>Add A Song</h1>
<%= form_for [@artist, @song] do |f| %>
  <%= f.label :name %>
  <%= f.text_area :name, required: true %>
  <br />
  <%= f.submit %>
<% end %>

app/views/songs/show.html.erb
<h3><%= @song.name %></h3>

<div class= right>
  <button class="silver btn-small"><%= link_to 'Edit', edit_chart_song_path([@chart, @song])%></button>
  <button class="silver btn-small"><%= link_to 'Delete', [@chart, @song], method: :delete%></button>
  <button class="silver btn-small"><%= link_to 'Back', chart_songs_path(@chart)%></button>
</div>